### ISSUE TITLE
General A11y Publication Checklist (created specifically for this sim, not a general template)

### ISSUE THREAD

**Issue by emily-phet** [phetsims/faradays-law#186]
# Other A11y ToDo's
**Maintain [Accessible Sims page](https://phet.colorado.edu/en/accessibility/prototypes)**
- [x] Use website admin page (or create issue) to add sim to to A11y Sims page once there is a working prototype.
- [x] Update link to prototype from time to time
  - [x] At Dev Testing
  - [x] At RC Testing
  - [ ] At publication (remove the prototype designation, and update info in sim section)

**Accessory Materials**
- [x] Create issue to update Teacher tips
- [x] Create issue to create Sound feature videos

**Pan / Zoom feature**
- [x] Anything to be done @jessegreenberg re pan/zoom?

**Check Credits**
- [x] Issue created to verify A11y team has been added, see #189 

**Interviews**
- [ ] Ensure interviews are recorded to this sim's interview spreadsheet
- [x] @terracoda added blank spread sheet to Multi-modal Features folder

**During QA or just after publication**
- [ ] List out main design challenges (if any and if necessary)
- [ ] List out lessons learned from this sim (e.g., found focus issues for iOS)

**Comment by terracoda** [comment]
Just a note that FL has bee added to the prototype list of sim through the web admin. I am not sure exactly when that will go live, but at least it is added. I used latest available dev version for the link. this can be updated as we progress through QA.

**Comment by terracoda** [comment]
I updated link to the FL on the A11y Sims page to the RC.1 link.
I also updated the icons to be: Alternative Input, Sonification, and Magnfication, but magnification is not sticking.
I removed "Interactive Description".

**Comment by jessegreenberg** [comment]
> Anything to be done @jessegreenberg re pan/zoom?

Pan and Zoom feature was enabled and verified by design team in #173. QA team tested the feature for release. I think that's it! @terracoda @emily-phet anything else for this?

**Comment by terracoda** [comment]
If pan & zoom passed QA, that's makes for a reliable stamp of approval from my perspective.

**Comment by emily-phet** [comment]
Agreed!

**Comment by jessegreenberg** [comment]
OK, closing then!
